// Copyright 2026 by Moshix
/**
 * Generate src/game/romdata.js: the three program ROMs, as base64, at
 * their CPU addresses, for the port to read tables where the 6809 did.
 *
 * Bring-up mode (now): every ROM byte is readable. Once the listing
 * generator has traced code versus data, it writes the same module shape
 * with a data bitmap (`mask`) and code bytes zeroed, and `romByte` then
 * throws on a code byte. `buildRomdataSource(roms, masks)` takes those
 * masks so either tool can emit the file.
 *
 *   node tools/gen-romdata.mjs          write src/game/romdata.js
 *   node tools/gen-romdata.mjs --check  exit 1 if the file is stale
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { loadGaplus, ROOT } from './romset.mjs';

export const OUT = join(ROOT, 'src', 'game', 'romdata.js');

/** Program ROM windows: [cpu, first address]; all end at $FFFF. */
export const WINDOWS = Object.freeze([
  ['main', 0xa000],
  ['sub', 0xa000],
  ['sound', 0xe000],
]);

/** @param {Uint8Array} b @returns {string} */
const b64 = (b) => Buffer.from(b).toString('base64');

/**
 * Wrap a long string into quoted, concatenated 76-column lines so the
 * generated file stays readable in an editor.
 * @param {string} s @returns {string}
 */
function wrap(s) {
  const lines = [];
  for (let i = 0; i < s.length; i += 70) lines.push(`'${s.slice(i, i + 70)}'`);
  return `    ${lines.join('\n    + ')}`;
}

/**
 * @param {{ main: Uint8Array, sub: Uint8Array, sound: Uint8Array }} roms
 *   64 KB CPU images (tools/romset.mjs loadGaplus)
 * @param {Partial<Record<'main'|'sub'|'sound', Uint8Array>>} [masks]
 *   data bitmaps (bit (a - base) set = data byte); absent = all data
 * @returns {string}
 */
export function buildRomdataSource(roms, masks = {}) {
  const parts = WINDOWS.map(([cpu, base]) => {
    const bytes = roms[/** @type {'main'} */ (cpu)].slice(base, 0x10000);
    const mask = masks[/** @type {'main'} */ (cpu)];
    if (mask) {
      // Code bytes are zeroed so the shipped file carries data only.
      for (let i = 0; i < bytes.length; i += 1) {
        if (!((mask[i >> 3] >> (i & 7)) & 1)) bytes[i] = 0;
      }
    }
    const hexBase = `0x${base.toString(16).toUpperCase()}`;
    return `  ${cpu}: {\n    base: ${hexBase},\n    data:\n${wrap(b64(bytes))},\n`
      + `    mask: ${mask ? `\n${wrap(b64(mask))}` : 'null'},\n  },`;
  });
  return `// Copyright 2026 by Moshix
// GENERATED by tools/gen-romdata.mjs from the gaplus ROM set -- do not edit.
/**
 * The program ROMs at their CPU addresses (main and sub $A000-$FFFF, sound
 * $E000-$FFFF). Game state holds ROM addresses (tables, strings, paths),
 * so the port reads data exactly where the 6809 did, never from copies.
 *
 * \`mask\` is a bitmap of the bytes that are data (bit i of byte i >> 3,
 * counted from \`base\`). While it is null every byte is readable (bring-up
 * mode); once the listing has separated code from data, reading a code
 * byte throws, because that can only be a porting mistake.
 *
 * Words are big-endian (6809): high byte at the lower address.
 * @see docs/porting-guide.md section 5
 */

/** @typedef {'main'|'sub'|'sound'} Cpu */

/** @param {string} s @returns {Uint8Array} */
function decode(s) {
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i += 1) out[i] = bin.charCodeAt(i);
  return out;
}

const RAW = {
${parts.join('\n')}
};

/**
 * @typedef {object} RomImage
 * @property {number} base first ROM address
 * @property {Uint8Array} data bytes from base to $FFFF
 * @property {Uint8Array|null} mask data bitmap, or null = all data
 */

/** @type {Record<Cpu, RomImage>} */
const ROMS = {
  main: { base: RAW.main.base, data: decode(RAW.main.data),
    mask: RAW.main.mask === null ? null : decode(RAW.main.mask) },
  sub: { base: RAW.sub.base, data: decode(RAW.sub.data),
    mask: RAW.sub.mask === null ? null : decode(RAW.sub.mask) },
  sound: { base: RAW.sound.base, data: decode(RAW.sound.data),
    mask: RAW.sound.mask === null ? null : decode(RAW.sound.mask) },
};

/** First ROM address of each CPU. */
export const ROM_BASE = Object.freeze({
  main: RAW.main.base, sub: RAW.sub.base, sound: RAW.sound.base,
});

/**
 * Is \`addr\` inside this CPU's ROM window?
 * @param {Cpu} cpu @param {number} addr @returns {boolean}
 */
export function isRom(cpu, addr) {
  return (addr & 0xffff) >= ROMS[cpu].base;
}

/**
 * Is the ROM byte at \`addr\` readable as data?
 * @param {Cpu} cpu @param {number} addr @returns {boolean}
 */
export function isData(cpu, addr) {
  const r = ROMS[cpu];
  const i = (addr & 0xffff) - r.base;
  if (i < 0) return false;
  return r.mask === null || ((r.mask[i >> 3] >> (i & 7)) & 1) === 1;
}

/**
 * One byte of a CPU's ROM, at its CPU address.
 * @param {Cpu} cpu @param {number} addr @returns {number}
 */
export function romByte(cpu, addr) {
  const r = ROMS[cpu];
  const a = addr & 0xffff;
  const i = a - r.base;
  const hex = a.toString(16).toUpperCase().padStart(4, '0');
  if (i < 0) throw new Error(\`\${cpu} $\${hex} is not ROM\`);
  if (r.mask !== null && !((r.mask[i >> 3] >> (i & 7)) & 1)) {
    throw new Error(\`\${cpu} ROM $\${hex} is code, not data\`);
  }
  return r.data[i];
}

/**
 * Big-endian word from ROM: \`ldx $nnnn\` / \`ldd ,x\` read the high byte
 * first. $FFFF+1 wraps to $0000, which is not ROM and throws.
 * @param {Cpu} cpu @param {number} addr @returns {number}
 */
export function romWord(cpu, addr) {
  return (romByte(cpu, addr) << 8) | romByte(cpu, (addr + 1) & 0xffff);
}

/** Main CPU ROM byte. @param {number} addr @returns {number} */
export const mainRom = (addr) => romByte('main', addr);
/** Sub CPU ROM byte. @param {number} addr @returns {number} */
export const subRom = (addr) => romByte('sub', addr);
/** Sound CPU ROM byte. @param {number} addr @returns {number} */
export const soundRom = (addr) => romByte('sound', addr);
/** Main CPU ROM word. @param {number} addr @returns {number} */
export const mainWord = (addr) => romWord('main', addr);
/** Sub CPU ROM word. @param {number} addr @returns {number} */
export const subWord = (addr) => romWord('sub', addr);
/** Sound CPU ROM word. @param {number} addr @returns {number} */
export const soundWord = (addr) => romWord('sound', addr);
`;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  const src = buildRomdataSource(loadGaplus());
  if (process.argv.includes('--check')) {
    let cur = '';
    try { cur = readFileSync(OUT, 'utf8'); } catch { /* missing */ }
    if (cur !== src) {
      console.error('src/game/romdata.js is stale; run tools/gen-romdata.mjs');
      process.exit(1);
    }
    console.log('src/game/romdata.js is up to date');
  } else {
    writeFileSync(OUT, src);
    console.log(`wrote ${OUT} (${src.length} bytes)`);
  }
}
